const express = require('express');
const router = express.Router();

const customerController = require('../controllers/customerController');
router.get('/',customerController.list);
router.get('/add',customerController.inserts);
router.post('/add',customerController.save);
router.get('/delete/:problem_id',customerController.delete);
router.get('/update/:problem_id',customerController.edit);
router.post('/update/:problem_id',customerController.update);
router.get('/OrdenDep',customerController.ordenDep);
router.get('/OrdenPro',customerController.ordenPro);
router.get('/OrdenMun',customerController.ordenMun);
router.get('/OrdenLoc',customerController.ordenLoc);
router.get('/OrdenFec',customerController.ordenFec);
router.get('/OrdenEsc',customerController.ordenEsc);
router.get('/BuscarDep',customerController.buscar_inicialDep);
router.get('/BuscarPro',customerController.buscar_inicialPro);
router.get('/BuscarMun',customerController.buscar_inicialMun);
router.get('/BuscarLoc',customerController.buscar_inicialLoc);
router.get('/BuscarFec',customerController.buscar_inicialFec);
router.get('/BuscarEsc',customerController.buscar_inicialEsc);
router.post('/BuscarDep',customerController.buscarDep);
router.post('/BuscarPro',customerController.buscarPro);
router.post('/BuscarMun',customerController.buscarMun);
router.post('/BuscarLoc',customerController.buscarLoc);
router.post('/BuscarFec',customerController.buscarFec);
router.post('/BuscarEsc',customerController.buscarEsc);

module.exports = router;